# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- template: build-temp.yaml
  parameters:
    name: Linux
    vmImage: 'Mahesh babu'
- template: realse-temp.yml


